version: 0.02

phases:
  pre_build:
    commands:
      - echo Logging into AWS ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build --platform linux/amd64 -t $IMAGE_REPO_URI:latest ./chat-app
      - docker tag $IMAGE_REPO_URI:latest $IMAGE_REPO_URI:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image...
      - docker push $IMAGE_REPO_URI:latest
      - docker push $IMAGE_REPO_URI:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Writing image definitions file...
      - printf \'[{"name":"chatter","imageUri":"%s"}]\' $IMAGE_REPO_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json